In [1]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
!curl https://www.youtube.com >> youtube.html

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100  794k    0  794k    0     0   546k      0 --:--:--  0:00:01 --:--:--  546k


In [ ]:
!cat youtube.html

In [10]:
import numpy as np

a = np.array([[1,2,3,],[12,34,56]])
print(a.reshape((3,2)))
print(np.ones((7,7)))

[[ 1  2]
 [ 3 12]
 [34 56]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
